#!/usr/bin/env bash

#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS         #
#                                   #
#####################################

# launch PowerShell with custom config for bspwm #

CONFIG="$HOME/.config/bspwm/alacritty/alacritty.toml"

alacritty --class 'alacritty-float,alacritty-float' --config-file "$CONFIG" -e pwsh-preview